metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

      
metricbeat.modules:
#------------------------------- Docker Module -------------------------------
- module: docker
  metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
  hosts: ["unix:///var/run/docker.sock"]
  enabled: true
  period: 5s

- module: postgresql
  enabled: true
  metricsets:
    - database
    - bgwriter
    - activity

  period: 10s

  hosts: ["postgres://Database-Server:5432"]
  username: admin
  password: secret




#-------------------------- Logstash output ------------------------------
output:
  logstash:
    enabled: true
    hosts:
      - logstash:5044


setup.dashboards.enabled: true  

setup.kibana:
    host: "kibana:5601"

# logging.level: warning
# logging.to_files: true
# logging.to_syslog: false
# logging.files:
#   path: /var/log/metricbeat
#   name: metricbeat.log
#   keepfiles: 2
#   permissions: 0644
