#metricbeat.config:
#  modules:
#    path: ${path.config}/modules.d/*.yml
#    reload.enabled: false

metricbeat.modules:
  - module: docker
    metricsets:
      - "container"
      - "cpu"
      - "diskio"
      - "event"
      - "healthcheck"
      - "info"
      - "image"
      - "memory"
      - "network"
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s
    enabled: true
  - module: system
    metricsets:
      - cpu             # CPU usage
      - load            # CPU load averages
      - memory          # Memory usage
      - network         # Network IO
      - process         # Per process metrics
      - process_summary # Process summary
      - uptime          # System Uptime
      - socket_summary  # Socket summary
      - core           # Per CPU core usage
      - diskio         # Disk IO
    enabled: true
    period: 10s
    processes: ['.*']

    # Configure the mount point of the host’s filesystem for use in monitoring a host from within a container
    #system.hostfs: "/hostfs"

    # Configure the metric types that are included by these metricsets.
    cpu.metrics:  ["percentages","normalized_percentages"]  # The other available option is ticks.
    core.metrics: ["percentages"]  # The other available option is ticks.
  - module: postgresql
    hosts: ["postgres://dbpostgres:5432?sslmode=disable"]
    metricsets:
      - database
      - bgwriter
      - activity
      - statement
    period: 10s
    enabled: true
    username: postgres
    password: postgres

setup.kibana:
  host: "kibana:5601"

setup.dashboards.enabled: true

output.elasticsearch:
  hosts: '[elasticsearch]'
